import { DICTIONARY, ScrabbleMods } from '@/ps/games/scrabble/constants';

import type { BaseModEntry } from '@/ps/games/mods';
import type { BaseBoard as BaseBoardType, LetterMetadata, WordScore } from '@/ps/games/scrabble/types';

export const ScrabbleModData: Record<
	ScrabbleMods,
	BaseModEntry & { dict: DICTIONARY; points?: LetterMetadata; counts?: LetterMetadata; board?: BaseBoardType }
> = {
	[ScrabbleMods.CSW19]: {
		id: ScrabbleMods.CSW19,
		name: 'CSW19',
		desc: 'Base Scrabble with the CSW19 dictionary.',
		dict: DICTIONARY.CSW19,
	},
	[ScrabbleMods.CSW21]: {
		id: ScrabbleMods.CSW21,
		name: 'CSW21',
		desc: 'Base Scrabble with the CSW21 dictionary.',
		dict: DICTIONARY.CSW21,
	},
	[ScrabbleMods.CSW24]: {
		id: ScrabbleMods.CSW24,
		name: 'CSW24',
		desc: 'Base Scrabble with the CSW24 dictionary.',
		dict: DICTIONARY.CSW24,
		aliases: ['current'],
	},
	[ScrabbleMods.ODS8]: {
		id: ScrabbleMods.ODS8,
		name: 'ODS8',
		desc: 'French variant of Scrabble.',
		dict: DICTIONARY.ODS8,
		counts: {
			A: 9,
			B: 2,
			C: 2,
			D: 3,
			E: 15,
			F: 2,
			G: 2,
			H: 2,
			I: 8,
			J: 1,
			K: 1,
			L: 5,
			M: 3,
			N: 6,
			O: 6,
			P: 2,
			Q: 1,
			R: 6,
			S: 6,
			T: 6,
			U: 6,
			V: 2,
			W: 1,
			X: 1,
			Y: 1,
			Z: 1,
			_: 2,
		},
		points: {
			A: 1,
			B: 3,
			C: 3,
			D: 2,
			E: 1,
			F: 4,
			G: 2,
			H: 4,
			I: 1,
			J: 8,
			K: 10,
			L: 1,
			M: 2,
			N: 1,
			O: 1,
			P: 3,
			Q: 8,
			R: 1,
			S: 1,
			T: 1,
			U: 1,
			V: 4,
			W: 10,
			X: 10,
			Y: 10,
			Z: 10,
			_: 0,
		},
		aliases: ['ods', 'french', 'francais', 'franais'],
	},
	[ScrabbleMods.CLABBERS]: {
		id: ScrabbleMods.CLABBERS,
		name: 'Clabbers',
		desc: 'Scrabble, but all anagrams are valid, too!',
		dict: DICTIONARY.CLABBERS,
	},
	[ScrabbleMods.POKEMON]: {
		id: ScrabbleMods.POKEMON,
		name: 'Pokémon',
		desc: 'Scrabble but Pokéwords are allowed (with bonus scoring)!',
		dict: DICTIONARY.CSW24,
		aliases: ['pokemod', 'pokmon', 'pkmn', 'mons'],
	},
	[ScrabbleMods.CRAZYMONS]: {
		id: ScrabbleMods.CRAZYMONS,
		name: 'CRAZYMONS',
		desc: 'PokéScrabble, but INsANe BONuSEs!',
		dict: DICTIONARY.CSW24,
		aliases: ['crazy'],
	},
	[ScrabbleMods.SUPER]: {
		id: ScrabbleMods.SUPER,
		name: 'Super Scrabble',
		desc: 'Super Scrabble, with a super board! See https://en.wikipedia.org/wiki/Super_Scrabble',
		dict: DICTIONARY.CSW24,
		counts: {
			A: 16,
			B: 4,
			C: 6,
			D: 8,
			E: 24,
			F: 4,
			G: 5,
			H: 5,
			I: 13,
			J: 2,
			K: 2,
			L: 7,
			M: 6,
			N: 13,
			O: 15,
			P: 4,
			Q: 2,
			R: 13,
			S: 10,
			T: 15,
			U: 7,
			V: 3,
			W: 4,
			X: 2,
			Y: 4,
			Z: 2,
			_: 4,
		},
		board: [],
		aliases: ['superscrabble'],
	},
};

export const POKEMON_SCORING: WordScore = [2, 10];
export const CRAZYMONS_SCORING: WordScore = [5, 0];
