#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

read -ra TO_PRETTIFY <<< "$(git diff --diff-filter=ACMTUXB --name-only --staged | grep -E -e '\.[jt]sx?$' -e '\.md$' -e '\.html$' -e '\.json$' || :)"
if (( ${#TO_PRETTIFY[@]} )); then npm run prettify "${TO_PRETTIFY[@]}"; fi
npm test
FAIL_ON_PENDING=true npm run notify-unpushed -- src/secrets
