name: Validity

on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    strategy:
      matrix:
        bun-version: [1.2.17]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: bun install
      - run: bun run test
